# Generated by Django 5.2.12 on 2026-03-28 14:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donations', '0001_initial'),
        ('donors', '0001_initial'),
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone Call'), ('meeting', 'In-Person Meeting'), ('note', 'Note'), ('letter', 'Letter/Mail'), ('sms', 'SMS/Text'), ('social_media', 'Social Media'), ('video_call', 'Video Call')], max_length=20)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], default='outbound', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('scheduled', 'Scheduled'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('replied', 'Replied'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True, help_text='Brief summary of the communication')),
                ('from_address', models.CharField(blank=True, max_length=255)),
                ('to_address', models.CharField(blank=True, max_length=255)),
                ('communication_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('delivered_date', models.DateTimeField(blank=True, null=True)),
                ('read_date', models.DateTimeField(blank=True, null=True)),
                ('requires_followup', models.BooleanField(default=False)),
                ('followup_date', models.DateTimeField(blank=True, null=True)),
                ('followup_completed', models.BooleanField(default=False)),
                ('sentiment', models.CharField(blank=True, help_text='positive, neutral, negative', max_length=20)),
                ('outcome', models.CharField(blank=True, help_text='pledge_made, donation_received, meeting_scheduled, etc.', max_length=50)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('thread_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='donors.donor')),
                ('related_donation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='donations.donation')),
                ('related_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='events.event')),
            ],
            options={
                'ordering': ['-communication_date'],
            },
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('was_answered', models.BooleanField(default=False)),
                ('went_to_voicemail', models.BooleanField(default=False)),
                ('call_quality', models.CharField(blank=True, help_text='excellent, good, fair, poor', max_length=20)),
                ('recording_url', models.URLField(blank=True)),
                ('call_outcome', models.CharField(blank=True, help_text='spoke_to_donor, left_message, no_answer, busy, wrong_number', max_length=50)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('communication', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='call_details', to='communications.communication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_opt_in', models.BooleanField(default=True)),
                ('phone_opt_in', models.BooleanField(default=True)),
                ('sms_opt_in', models.BooleanField(default=False)),
                ('mail_opt_in', models.BooleanField(default=True)),
                ('preferred_frequency', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually'), ('as_needed', 'As Needed')], default='monthly', max_length=20)),
                ('preferred_topics', models.JSONField(blank=True, default=list)),
                ('exclude_topics', models.JSONField(blank=True, default=list)),
                ('preferred_contact_time', models.CharField(blank=True, help_text='morning, afternoon, evening', max_length=50)),
                ('timezone', models.CharField(default='America/New_York', max_length=50)),
                ('do_not_contact', models.BooleanField(default=False)),
                ('do_not_contact_reason', models.TextField(blank=True)),
                ('do_not_contact_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='communication_preference', to='donors.donor')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('template_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('letter', 'Letter')], max_length=20)),
                ('subject_template', models.CharField(blank=True, max_length=255)),
                ('body_template', models.TextField()),
                ('category', models.CharField(blank=True, help_text='thank_you, welcome, reminder, etc.', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('available_variables', models.JSONField(blank=True, default=list, help_text='List of available template variables')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True)),
                ('template_context', models.JSONField(blank=True, default=dict)),
                ('is_automated', models.BooleanField(default=False)),
                ('automation_trigger', models.CharField(blank=True, help_text='new_donor, first_donation, lapsed_donor, etc.', max_length=50)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_communications', to='donors.donor')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_uses', to='communications.communicationtemplate')),
            ],
            options={
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['donor', 'communication_date'], name='communicati_donor_i_d14c07_idx'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['communication_type', 'communication_date'], name='communicati_communi_929ce2_idx'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['status', 'requires_followup'], name='communicati_status_c94b21_idx'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['thread_id'], name='communicati_thread__94083e_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationtemplate',
            index=models.Index(fields=['template_type', 'category'], name='communicati_templat_0b291b_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationtemplate',
            index=models.Index(fields=['is_active'], name='communicati_is_acti_8db4df_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationschedule',
            index=models.Index(fields=['donor', 'scheduled_date'], name='communicati_donor_i_aee51b_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationschedule',
            index=models.Index(fields=['status', 'scheduled_date'], name='communicati_status_adc155_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationschedule',
            index=models.Index(fields=['is_automated', 'status'], name='communicati_is_auto_92501c_idx'),
        ),
    ]
