# Generated by Django 5.2.12 on 2026-03-28 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('layout_config', models.JSONField(blank=True, default=dict, help_text='Dashboard layout configuration')),
                ('widgets', models.JSONField(blank=True, default=list, help_text='Widget configurations')),
                ('is_default', models.BooleanField(default=False, help_text='Default dashboard for user')),
                ('is_shared', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MetricDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('entity_type', models.CharField(choices=[('donor', 'Donor'), ('donation', 'Donation'), ('campaign', 'Campaign'), ('event', 'Event'), ('communication', 'Communication')], max_length=20)),
                ('calculation_type', models.CharField(choices=[('count', 'Count'), ('sum', 'Sum'), ('avg', 'Average'), ('min', 'Minimum'), ('max', 'Maximum'), ('distinct_count', 'Distinct Count'), ('custom', 'Custom')], max_length=20)),
                ('field_name', models.CharField(blank=True, help_text='Field to aggregate', max_length=100)),
                ('custom_formula', models.TextField(blank=True, help_text='Custom calculation formula')),
                ('format_string', models.CharField(default='{value}', help_text='Format string for display', max_length=50)),
                ('unit', models.CharField(blank=True, help_text='$, %, etc.', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False, help_text='System metric, cannot be deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['entity_type', 'name'],
                'indexes': [models.Index(fields=['entity_type', 'is_active'], name='reports_met_entity__28527f_idx'), models.Index(fields=['slug'], name='reports_met_slug_e9c5cd_idx')],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('donor_analytics', 'Donor Analytics'), ('donation_summary', 'Donation Summary'), ('campaign_performance', 'Campaign Performance'), ('ltv_analysis', 'Lifetime Value Analysis'), ('retention_analysis', 'Retention Analysis'), ('event_analytics', 'Event Analytics'), ('communication_analytics', 'Communication Analytics'), ('custom', 'Custom Report')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('filters', models.JSONField(blank=True, default=dict, help_text='Report filters configuration')),
                ('group_by', models.JSONField(blank=True, default=list, help_text='Grouping configuration')),
                ('metrics', models.JSONField(blank=True, default=list, help_text='Metrics to include')),
                ('sort_order', models.JSONField(blank=True, default=list, help_text='Sort configuration')),
                ('date_range_start', models.DateField(blank=True, null=True)),
                ('date_range_end', models.DateField(blank=True, null=True)),
                ('date_range_preset', models.CharField(blank=True, choices=[('today', 'Today'), ('yesterday', 'Yesterday'), ('this_week', 'This Week'), ('last_week', 'Last Week'), ('this_month', 'This Month'), ('last_month', 'Last Month'), ('this_quarter', 'This Quarter'), ('last_quarter', 'Last Quarter'), ('this_year', 'This Year'), ('last_year', 'Last Year'), ('last_30_days', 'Last 30 Days'), ('last_90_days', 'Last 90 Days'), ('last_12_months', 'Last 12 Months'), ('all_time', 'All Time'), ('custom', 'Custom Range')], max_length=20)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('schedule_frequency', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], max_length=20)),
                ('schedule_day_of_week', models.PositiveSmallIntegerField(blank=True, help_text='0=Monday, 6=Sunday', null=True)),
                ('schedule_day_of_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('schedule_recipients', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_favorite', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportExecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('result_data', models.JSONField(blank=True, default=dict, help_text='Report results')),
                ('result_summary', models.JSONField(blank=True, default=dict, help_text='Summary statistics')),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('output_format', models.CharField(choices=[('json', 'JSON'), ('csv', 'CSV'), ('xlsx', 'Excel'), ('pdf', 'PDF')], default='json', max_length=10)),
                ('output_file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('execution_time_seconds', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='reports.report')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['report_type', 'is_active'], name='reports_rep_report__a0ff1c_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['created_by', 'is_favorite'], name='reports_rep_created_f1f458_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexecution',
            index=models.Index(fields=['report', 'status'], name='reports_rep_report__7001c2_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexecution',
            index=models.Index(fields=['created_at'], name='reports_rep_created_06b8b7_idx'),
        ),
    ]
